pipeline:
  build:
    image: docker
    privileged: true
    group: build
    commands:
      - docker build -t build-speed-demo-build -f Dockerfile.build .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  lint:
    image: docker
    privileged: true
    group: build
    commands:
      - docker build -t build-speed-demo-lint -f Dockerfile.lint .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  test:
    image: docker
    privileged: true
    group: test
    commands:
      - docker build -t build-speed-demo-test -f Dockerfile.test .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  e2e:
    image: docker
    privileged: true
    group: test
    commands:
      - docker build -t build-speed-demo-e2e -f Dockerfile.e2e .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  publish_staging:
    image: docker
    privileged: true
    group: deploy
    commands:
      - docker build -t no0dles/angular-build-speed-demo:staging .
      - docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
      - docker push no0dles/angular-build-speed-demo:staging
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      event: deployment
      environment: staging

  publish_production:
    image: docker
    privileged: true
    group: deploy
    commands:
      - docker build -t no0dles/angular-build-speed-demo:production .
      - docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
      - docker push no0dles/angular-build-speed-demo:production
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      event: deployment
      environment: production
