pipeline:

  build_dev:
    image: docker
    privileged: true
    group: build
    commands:
      - docker build --build-arg ENV=dev -t build-speed-demo-build -f Dockerfile.build .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  build_staging:
    image: docker
    privileged: true
    group: build
    commands:
      - docker build --build-arg ENV=staging -t build-speed-demo-build -f Dockerfile.build .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  build_prod:
    image: docker
    privileged: true
    group: build
    commands:
      - docker build --build-arg ENV=prod -t build-speed-demo-build -f Dockerfile.build .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  lint:
    image: docker
    privileged: true
    group: build
    commands:
      - docker build -t build-speed-demo-lint -f Dockerfile.lint .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  test:
    image: docker
    privileged: true
    group: test
    commands:
      - docker build -t build-speed-demo-test -f Dockerfile.test .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  e2e:
    image: docker
    privileged: true
    group: test
    commands:
      - docker build -t build-speed-demo-e2e -f Dockerfile.e2e .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  publish_staging:
    image: docker
    privileged: true
    commands:
      - docker login -u no0dles -p $DOCKER_PASSWORD
      - docker build --build-arg ENV=staging -t no0dles/angular-build-speed-demo:staging -t no0dles/angular-build-speed-demo:staging-$DRONE_COMMIT .
      - docker push no0dles/angular-build-speed-demo:staging-$DRONE_COMMIT
      - docker push no0dles/angular-build-speed-demo:staging
    secrets: [DOCKER_PASSWORD]
    when:
      branch: develop
      event: [ push, tag ]
      status: [ success ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  publish_production:
    image: docker
    privileged: true
    commands:
      - docker login -u no0dles -p $DOCKER_PASSWORD
      - docker build --build-arg ENV=prod -t no0dles/angular-build-speed-demo:production -t no0dles/angular-build-speed-demo:production-$DRONE_COMMIT .
      - docker push no0dles/angular-build-speed-demo:production-$DRONE_COMMIT
      - docker push no0dles/angular-build-speed-demo:production
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets: [DOCKER_PASSWORD]
    when:
      branch: master
      event: [ push, tag ]
      status: [ success ]

  deploy_production:
    image: no0dles/swarm-deploy-plugin:latest
    url: https://deployment.swarm.bertschi.io/deployment
    service_id: $SERVICE_ID
    tag: no0dles/angular-build-speed-demo:production-$DRONE_COMMIT
    secrets: [SERVICE_ID]
    when:
      branch: master
      event: [ push, tag ]
      status: [ success ]
