pipeline:
  build:
    image: docker
    privileged: true
    commands:
      - docker build -t build-speed-demo-build -f Dockerfile.build .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  lint:
    image: docker
    privileged: true
    commands:
      - docker build -t build-speed-demo-lint -f Dockerfile.lint .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  test:
    image: docker
    privileged: true
    commands:
      - docker build -t build-speed-demo-test -f Dockerfile.test .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  e2e:
    image: docker
    privileged: true
    commands:
      - docker build -t build-speed-demo-e2e -f Dockerfile.e2e .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
