FROM node:8.1.3

WORKDIR /app

COPY package.json .
COPY yarn.lock .
RUN yarn install

COPY .angular-cli.json .
COPY tsconfig.json .
COPY src ./src

FROM node:8.1.3 as dev
RUN yarn build-dev

FROM node:8.1.3 as staging
RUN yarn build-staging

FROM node:8.1.3 as prod
RUN yarn build-prod
